var patternInd = [];
patternInd[0] = ["1", "1", "1"]; // 1
patternInd[1] = [null, "1", "1", "1"];
patternInd[2] = [null, null, "1", "1", "1"];
patternInd[3] = ["2", "2", "1", "1", "1"]; // 1 + 2
patternInd[4] = ["1", "1", "1", null, null, "2", null, null, null, null, "2"];
patternInd[5] = [null, "1", "1", "1", null, null, "2", null, null, null, null, "2"];
patternInd[6] = [null, null, "1", "1", "1", null, null, "2", null, null, null, null, "2"];
patternInd[7] = ["1", "1", "1", null, null, "2", null, null, null, null, null, null, null, null, null, "2"]; // 1 + 3
patternInd[8] = [null, "1", "1", "1", null, null, "2", null, null, null, null, null, null, null, null, null, "2"];
patternInd[9] = [null, null, "1", "1", "1", null, null, "2", null, null, null, null, null, null, null, null, null, "2"];
patternInd[10] = ["1", "1", "1", null, null, null, null, "2", null, null, null, null, null, null, null, null, null, "2"];
patternInd[11] = [null, "1", "1", "1", null, null, null, null, "2", null, null, null, null, null, null, null, null, null, "2"];
patternInd[12] = [null, null, "1", "1", "1", null, null, null, null, "2", null, null, null, null, null, null, null, null, null, "2"];
patternInd[13] = ["1", "1", "1", "2", null, null, null, null, null, null, null, null, null, "2"]; // 1 + 4
patternInd[14] = [null, "1", "1", "1", "2", null, null, null, null, null, null, null, null, null, "2"];
patternInd[15] = ["2", "1", "1", "1", null, null, null, null, null, null, "2"];
patternInd[16] = [null, "2", "1", "1", "1", null, null, null, null, null, null, "2"];
patternInd[17] = ["1", "1", null, "1", null, null, "2", null, null, null, null, "2", null, null, null, null, "2"]; // 1 + 5
patternInd[18] = [null, "1", "1", null, "1", null, null, "2", null, null, null, null, "2", null, null, null, null, "2"];
patternInd[19] = ["1", "1", null, "1", null, "2", null, null, null, null, "2", null, null, null, null, "2"]; // 1 + 6
patternInd[20] = [null, "1", "1", null, "1", null, "2", null, null, null, null, "2", null, null, null, null, "2"];
patternInd[21] = ["1", "1", null, null, "1", null, "2", null, null, null, null, "2", null, null, null, null, "2"]; // 1 + 7
patternInd[22] = ["1", "1", null, null, "1", "2", null, null, null, null, "2", null, null, null, null, "2"]; // 1 + 8
patternInd[23] = ["2", "1", "1", "1", null, "2"]; // 1 + 9
patternInd[24] = [null, "2", "1", "1", "1", null, "2"];
patternInd[25] = ["1", "1", "1", "2", null, null, null, null, "2"];
patternInd[26] = [null, "1", "1", "1", "2", null, null, null, null, "2"];
patternInd[27] = ["1", "2", "1", "2"]; // 3 + 3
patternInd[28] = [null, "1", "2", "1", "2"];
patternInd[29] = ["1", "1", null, null, null, "1"]; // 15
patternInd[30] = [null, "1", "1", null, null, null, "1"];
patternInd[31] = [null, null, "1", "1", null, null, null, "1"];
patternInd[32] = [null, null, null, "1", "1", null, null, null, "1"];
patternInd[33] = ["1", null, "1", null, null, "1"]; // 16
patternInd[34] = [null, "1", null, "1", null, null, "1"];
patternInd[35] = [null, null, "1", null, "1", null, null, "1"];
patternInd[36] = ["1", null, null, "1", null, "1"]; // 17
patternInd[37] = [null, "1", null, null, "1", null, "1"];
patternInd[38] = ["1", null, null, null, "1", "1"]; // 18
patternInd[39] = ["1", "2", null, "2", "1"]; // 14 + 3
patternInd[40] = ["1", "2", "2", "1", null]; // 12 + 2
patternInd[41] = [null, "1", "2", "2", "1"];
patternInd[42] = ["1", "1", null, null, null, "2", "2"]; // 9 + 9
patternInd[43] = [null, "1", "1", null, null, null, "2", "2"];
patternInd[44] = [null, null, "1", "1", null, null, null, "2", "2"];
patternInd[45] = [null, null, null, "1", "1", null, null, null, "2", "2"];
patternInd[46] = ["1", "1", null, null, null, "1", "1"]; // 9 + 9
patternInd[47] = [null, "1", "1", null, null, null, "1", "1"];
patternInd[48] = [null, null, "1", "1", null, null, null, "1", "1"];
patternInd[49] = [null, null, null, "1", "1", null, null, null, "1", "1"];

var patternIndSol = [];
patternIndSol[0] = ["0", "1", "0"]; // 1
patternIndSol[1] = [null, "0", "1", "0"];
patternIndSol[2] = [null, null, "0", "1", "0"];
patternIndSol[3] = ["0", "2", "0", "1", "0"]; // 1 + 2
patternIndSol[4] = ["0", "1", "0", null, null, "2", null, null, null, null, "0"];
patternIndSol[5] = [null, "0", "1", "0", null, null, "2", null, null, null, null, "0"];
patternIndSol[6] = [null, null, "0", "1", "0", null, null, "2", null, null, null, null, "0"];
patternIndSol[7] = ["0", "1", "0", null, null, "2", null, null, null, null, null, null, null, null, null, "0"]; // 1 + 3
patternIndSol[8] = [null, "0", "1", "0", null, null, "2", null, null, null, null, null, null, null, null, null, "0"];
patternIndSol[9] = [null, null, "0", "1", "0", null, null, "2", null, null, null, null, null, null, null, null, null, "0"];
patternIndSol[10] = ["0", "1", "0", null, null, null, null, "2", null, null, null, null, null, null, null, null, null, "0"];
patternIndSol[11] = [null, "0", "1", "0", null, null, null, null, "2", null, null, null, null, null, null, null, null, null, "0"];
patternIndSol[12] = [null, null, "0", "1", "0", null, null, null, null, "2", null, null, null, null, null, null, null, null, null, "0"];
patternIndSol[13] = ["0", "1", "0", "2", null, null, null, null, null, null, null, null, null, "0"]; // 1 + 4
patternIndSol[14] = [null, "0", "1", "0", "2", null, null, null, null, null, null, null, null, null, "0"];
patternIndSol[15] = ["2", "0", "1", "0", null, null, null, null, null, null, "0"];
patternIndSol[16] = [null, "2", "0", "1", "0", null, null, null, null, null, null, "0"];
patternIndSol[17] = ["0", "1", null, "0", null, null, "0", null, null, null, null, "2", null, null, null, null, "0"]; // 1 + 5
patternIndSol[18] = [null, "0", "1", null, "0", null, null, "0", null, null, null, null, "2", null, null, null, null, "0"];
patternIndSol[19] = ["1", "0", null, "0", null, "0", null, null, null, null, "2", null, null, null, null, "0"]; // 1 + 6
patternIndSol[20] = [null, "1", "0", null, "0", null, "0", null, null, null, null, "2", null, null, null, null, "0"];
patternIndSol[21] = ["0", "1", null, null, "0", null, "0", null, null, null, null, "2", null, null, null, null, "0"]; // 1 + 7
patternIndSol[22] = ["1", "0", null, null, "0", "0", null, null, null, null, "2", null, null, null, null, "0"]; // 1 + 8
patternIndSol[23] = ["2", "0", "1", "0", null, "0"]; // 1 + 9
patternIndSol[24] = [null, "2", "0", "1", "0", null, "0"];
patternIndSol[25] = ["0", "1", "0", "2", null, null, null, null, "0"];
patternIndSol[26] = [null, "0", "1", "0", "2", null, null, null, null, "0"];
patternIndSol[27] = ["0", "2", "1", "0"]; // 3 + 3
patternIndSol[28] = [null, "0", "2", "1", "0"];
patternIndSol[29] = ["0", "1", null, null, null, "1"]; // 15
patternIndSol[30] = [null, "0", "1", null, null, null, "1"];
patternIndSol[31] = [null, null, "0", "1", null, null, null, "1"];
patternIndSol[32] = [null, null, null, "0", "1", null, null, null, "1"];
patternIndSol[33] = ["0", null, "1", null, null, "1"]; // 16
patternIndSol[34] = [null, "0", null, "1", null, null, "1"];
patternIndSol[35] = [null, null, "0", null, "1", null, null, "1"];
patternIndSol[36] = ["0", null, null, "1", null, "1"]; // 17
patternIndSol[37] = [null, "0", null, null, "1", null, "1"];
patternIndSol[38] = ["0", null, null, null, "1", "1"]; // 18
patternIndSol[39] = ["0", "2", null, "0", "1"]; // 14 + 3
patternIndSol[40] = ["0", "2", "0", "1", null]; // 12 + 2
patternIndSol[41] = [null, "0", "2", "0", "1"];
patternIndSol[42] = ["0", "1", null, null, null, "2", "0"]; // 9 + 9
patternIndSol[43] = [null, "0", "1", null, null, null, "2", "0"];
patternIndSol[44] = [null, null, "0", "1", null, null, null, "2", "0"];
patternIndSol[45] = [null, null, null, "0", "1", null, null, null, "2", "0"];
patternIndSol[46] = ["0", "1", null, null, null, "1", "0"]; // 9 + 9
patternIndSol[47] = [null, "0", "1", null, null, null, "1", "0"];
patternIndSol[48] = [null, null, "0", "1", null, null, null, "1", "0"];
patternIndSol[49] = [null, null, null, "0", "1", null, null, null, "1", "0"];

